apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
    spec:
      containers:
      - name: todo-container
        image: jwalitha/todo-app:latest
        imagePullPolicy: Always   # 👈 Tells Kubernetes not to pull from Docker Hub
        ports:
        - containerPort: 80
