name: CI - Build and Deploy ToDo App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker Image
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/todo_updates:latest .

      # Step 4: Push Docker Image
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/todo_updates:latest

      # Step 5: Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # Step 6: Decode and Save Kubeconfig
      - name: Decode Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config

      # Optional Debug Step (verify kubeconfig)
      - name: Verify Kubeconfig
        run: |
          ls -la $HOME/.kube
          head -n 10 $HOME/.kube/config

      # Step 7: Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: kubectl apply -f todo-deployment.yaml
